# Generated by Django 6.0.2 on 2026-03-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'در انتظار پرداخت'), ('Processing', 'در حال آماده سازی سفارش'), ('On The Way', 'در حال ارسال به سمت مشتری'), ('Delivered', 'تحویل مشتری داده شد'), ('Canceled', 'سفارش لغو شده است')], default='Pending'),
        ),
    ]
