# Generated by Django 6.0.2 on 2026-02-18 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=10000)),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برند ها',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='PharmacyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_fullname', models.CharField(max_length=100)),
                ('doctor_info', models.TextField(max_length=10000)),
                ('pharmacy_phone1', models.CharField(max_length=25)),
                ('pharmacy_phone2', models.CharField(max_length=25)),
                ('pharmacy_phone3', models.CharField(max_length=25)),
                ('pharmacy_email1', models.EmailField(max_length=100)),
                ('pharmacy_email2', models.EmailField(max_length=100)),
                ('pharmacy_email3', models.EmailField(max_length=100)),
                ('pharmacy_address', models.TextField(max_length=10000)),
            ],
            options={
                'verbose_name': 'مشخصات داروخانه',
                'verbose_name_plural': 'مشخصات داروخانه',
            },
        ),
        migrations.CreateModel(
            name='CustomerDeliveryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('address', models.TextField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('shopping_cart', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مشخصات ارسال سفارش مشتری',
                'verbose_name_plural': 'مشخضات ارسال سفارش مشتریان',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('extra_info', models.TextField(blank=True, max_length=10000)),
                ('picture', models.ImageField(upload_to='upload/products/')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('is_sale', models.BooleanField(default=False)),
                ('sale_price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
