# Generated by Django 6.0.2 on 2026-03-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pharmacyinfo_about_pharmacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdeliveryinfo',
            name='shopping_cart',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
